#!/bin/bash
./assign2 3 t0.txt | grep OFF > 0.txt
./assign2 7 t1.txt | grep OFF > 1.txt
./assign2 8 t2.txt | grep OFF > 2.txt
./assign2 5 t3.txt | grep OFF > 3.txt 
./assign2 12 t4.txt | grep OFF > 4.txt

diff t0_sol.txt 0.txt
diff t1_sol.txt 1.txt
diff t2_sol.txt 2.txt
diff t3_sol.txt 3.txt
diff t4_sol.txt 4.txt
